[project]
name = "ivim"
version = "1.0.0"
description = "Tools related to Intravoxel Incoherent Motion (IVIM) modeling of diffusion MRI data"
readme = "README.md"
authors = [
            {name = "Oscar Jalnefjord", email = "oscar.jalnefjord@gu.se"}
            ]
license = { file = "LICENSE"}
classifiers = [ 
            "Intended Audience :: Developers", 
            "Intended Audience :: Science/Research", 
            "Topic :: Scientific/Engineering", 
            "Operating System :: OS Independent", 
            "License :: OSI Approved :: BSD-3-Clause License", 
            "Programming Language :: Python", 
            "Programming Language :: Python :: 3",
            ]
keywords = [ 
            "python", 
            "IVIM", 
            "intravoxel incoherent motion", 
            "perfusion", 
            "diffusion", 
            "MRI"
            ]
dependencies = [ 
            "numpy < 2", 
            "scipy", 
            "nibabel"]
requires-python = ">=3.10"

[project.optional-dependencies]
tests = [ "pytest", ]
docs = [ "sphinx", "sphinx-rtd-theme", "ipykernel", "nbsphinx", "sphinx-copybutton", "pandoc", "matplotlib",]

[project.urls]
Homepage = "https://ivim.readthedocs.io/"


[tool.coverage.run]
omit = [
    "tests/*"
]

[tool.setuptools.packages.find]
where = [ "ivim",]
